# Generated by Django 4.0.2 on 2022-02-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='mile date')),
                ('time', models.CharField(choices=[('M', 'Morning'), ('L', 'Lunch'), ('N', 'Night')], default='M', max_length=1)),
            ],
            options={
                'ordering': ('-date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('year', models.IntegerField()),
                ('accessories', models.ManyToManyField(to='main_app.Accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.motorcycle')),
            ],
        ),
        migrations.DeleteModel(
            name='moto',
        ),
        migrations.AddField(
            model_name='mile',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.motorcycle'),
        ),
    ]
