# Generated by Django 4.0.2 on 2022-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory_mile_motorcycle_photo_delete_moto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mile',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='mile',
            name='time',
        ),
        migrations.AddField(
            model_name='accessory',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mile',
            name='date',
            field=models.DateField(verbose_name='Ride Date'),
        ),
    ]
